const transforms = {
  'matrix': '(n,n,n,n,n,n)',
  'matrix3': '(n,n,n,n,n,n,n,n,n,n,n,n,n,n,n,n)',
  'translate': '(x,y)',
  'translate3d': '(x,y,z)',
  'translateX': '(x)',
  'translateY': '(y)',
  'translateZ': '(z)',
  'scale': '(x,y)',
  'scale3d': '(x,y,z)',
  'scaleX': '(x)',
  'scaleY': '(y)',
  'scaleZ': '(z)',
  'rotate': '(angle)',
  'rotate3d': '(x,y,z,angle)',
  'rotateX': '(angle)',
  'rotateY': '(angle)',
  'rotateZ': '(angle)',
  'skew': '(x-angle,y-angle)',
  'skewX': '(angle)',
  'skewY': '(angle)',
  'perspective': '(n)',
}

export default transforms;
